'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AsmGPP

    '''<summary>
    '''lblYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblYear As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLocationName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocationName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLicenseNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLicenseNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLicensee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLicensee As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLicenseStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLicenseStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStartDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExpireDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpireDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdLocationUID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdLocationUID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdRequestUID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdRequestUID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdGPPUID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdGPPUID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''UpdatePanelGPP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelGPP As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''imgS1Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark1Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark1Q1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS1Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkS1Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkS1Q2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optS1Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q2 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark1Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark1Q2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS1Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q3 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark1Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark1Q3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS1Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q4 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q4 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark1Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark1Q4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS1Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q5 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q5 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark1Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark1Q5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS1Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q6 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q6 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark1Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark1Q6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS1Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q7 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q7 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark1Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark1Q7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS1Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q8 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q8 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark1Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark1Q8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS1Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS1Q9 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS1Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS1Q9 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS1Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS1Q9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark1Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark1Q9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRemark1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSumScoreS1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumScoreS1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPercent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercent1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS2Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS2Q1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkS2Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkS2Q1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optS2Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS2Q1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS2Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS2Q1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark2Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark2Q1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS2Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS2Q2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS2Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS2Q2 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS2Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS2Q2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark2Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark2Q2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS2Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS2Q3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS2Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS2Q3 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS2Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS2Q3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark2Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark2Q3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS2Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS2Q4 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS2Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS2Q4 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS2Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS2Q4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark2Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark2Q4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS2Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS2Q5 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS2Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS2Q5 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS2Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS2Q5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark2Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark2Q5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS2Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS2Q6 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS2Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS2Q6 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS2Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS2Q6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark2Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark2Q6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRemark2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSumScoreS2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumScoreS2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPercent2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercent2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS3Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS3Q1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS3Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS3Q1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS3Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS3Q1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark3Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark3Q1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS3Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS3Q2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkS3Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkS3Q2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optS3Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS3Q2 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS3Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS3Q2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark3Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark3Q2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS3Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS3Q3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS3Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS3Q3 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS3Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS3Q3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark3Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark3Q3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS3Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS3Q4 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkS3Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkS3Q4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optS3Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS3Q4 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS3Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS3Q4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark3Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark3Q4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS3Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS3Q5 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkS3Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkS3Q5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optS3Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS3Q5 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS3Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS3Q5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark3Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark3Q5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRemark3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSumScoreS3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumScoreS3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPercent3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercent3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS4Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark4Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark4Q1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS4Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q2 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark4Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark4Q2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS4Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q3 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark4Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark4Q3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS4Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q4 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q4 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark4Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark4Q4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS4Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q5 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q5 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark4Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark4Q5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS4Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q6 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q6 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark4Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark4Q6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS4Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS4Q7 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS4Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS4Q7 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS4Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS4Q7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark4Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark4Q7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRemark4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSumScoreS4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumScoreS4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPercent4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercent4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgS5Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q1 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q1 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark5Q1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark5Q1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS5Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q2 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark5Q2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark5Q2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS5Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q3 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q3 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark5Q3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark5Q3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS5Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q4 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q4 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark5Q4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark5Q4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS5Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q5 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q5 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark5Q5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark5Q5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS5Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q6 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q6 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark5Q6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark5Q6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS5Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q7 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkS5Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkS5Q7 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optS5Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q7 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q7 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark5Q7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark5Q7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS5Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q8 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q8 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q8 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark5Q8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark5Q8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS5Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q9 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q9 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q9 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark5Q9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark5Q9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS5Q10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q10 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkS5Q10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkS5Q10 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optS5Q10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q10 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q10 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark5Q10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark5Q10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS5Q11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q11 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''chkS5Q11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkS5Q11 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''optS5Q11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q11 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark5Q11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark5Q11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgS5Q12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgS5Q12 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''optS5Q12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents optS5Q12 As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblScoreS5Q12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblScoreS5Q12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark5Q12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark5Q12 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRemark5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSumScoreS5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumScoreS5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPercent5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercent5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnDoc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtDocumentName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocumentName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''FileUpload2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload2 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''cmdAddFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddFile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanelDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanelDocument As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''grdDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdDocument As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''chkRisk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRisk As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''txtRiskRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRiskRemark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblPercentGroup1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercentGroup1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPercentGroup2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercentGroup2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPercentGroup3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercentGroup3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPercentGroup4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercentGroup4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPercentGroup5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercentGroup5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPercentage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdTotalScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdTotalScore As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdNetScore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdNetScore As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblResultRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResultRemark As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdClose As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdReOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdReOpen As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdPrint As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblTopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTopic As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdAccID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdAccID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''cmdUpImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpImg As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grdImg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdImg As Global.System.Web.UI.WebControls.GridView
End Class
